class MarkdownText:
    def __init__(self, text: str = "") -> None: ...
    def escaped_text(self) -> str: ...
    def __add__(self, other: MarkdownText | str) -> MarkdownText: ...

class InlineUrl(MarkdownText):
    def __init__(self, text: str, url: str) -> None: ...

class Italic(MarkdownText):
    def __init__(self, text: str) -> None: ...
